### ISSUE TITLE
詢問文件中沒有的使用方法

### ISSUE THREAD

**Issue by hubuki** [DevinY/dlaravel#3]
您好，因為部落格一直註冊失敗，所以來這邊發issue，請見諒><
想請問

1. 如果第一次不靠 ./create {new_project} 的方式，該如何 pull image 和啟動 container ?
2. 現在 ./create --db {project_name} 啟動的資料庫從資料庫名字到資料庫帳號、密碼都是 {project_name}，有沒有什麼辦法可以讓帳密固定是 homestead/secret 呢？

謝謝

**Comment by DevinY** [comment]
1. ./console up時會自動下載docker-compose.yml內所定義的images，如果還未下載過。你也透過docker官方指令下載，例如：
        docker pull deviny/fpm:7.1.10

2. D-Laravel可同時啟動多個*.dev 的域名，./create {project}會依你的Project名稱自動幫你建好資料庫及DB的連線及資料庫設定，所以不會使用固定的homestead/secret。

你可以使用laravel installer手動方式建立laravel的Project到sites資料夾，在調整.env的DB連線127.0.0.1為db，這樣既是固定的homestead。

./create --db {project_name} 單純提供一個簡易的方式幫您建立資料庫。
例如：安裝非laravel的project，像是Wordpress，phpbb或是用composer 安裝舊版的laravel。

**Comment by DevinY** [comment]
剛好出國不方便回，目前./create --db都是使用帳號密碼都是project的名稱，所以不會讓密碼固定在homestead/secret。在修改Laravel的.env時，較好記也較好輸入。
這個問題我Close了，如果您還有疑問，歡迎提出哦。
