### ISSUE TITLE
使用方式疑問

### ISSUE THREAD

**Issue by hubuki** [DevinY/dlaravel#5]
您好，因為部落格的登入功能無法使用故在這邊詢問

想請問如果已經在舊的版本產生了 example.dev 的網域的話，要如何改成現在的 example.test 呢？
我直接用 ./create --host example 會產生出 127.0.0.1 example.test 到 hosts，但是直接連結會變成 "It works!"

另外 ./console secure 所鎖定的對象 project 是以什麼為基準呢？我將 project的目錄從 ./sites 改成別的了是否有影響？ 

謝謝

**Comment by DevinY** [comment]
答:可用vim使用root身份修改，/etc/hosts，或者也可以用sed調整。

可先試跑可用如下指令看結果是否變更成功:
sudo sed 's/\.dev$/\.test/g' /etc/hosts

加入-i的參數就真的會直接改/etc/hosts檔了，
可以看見將所有.dev結尾的字都改為.test。

MacOS指令如下:
sudo sed -i.bak 's/\.dev$/\.test/g' /etc/hosts

完成後可以cat /etc/hosts查看。
如果在Linux的環境，指令可以
sudo sed -i 's/\.dev$/\.test/g' /etc/hosts

是否可以自己變更sites資料夾?
答: 不行 ，因為nginx的設定檔etc/default.conf都是指向sites資料夾的，因此Project需放在sites資料夾內。

./console secure會依sites資料夾的目錄產生域名，及self-signed的SAN憑證 ，也就是如果在sites中有一百個Project，那一百個Project都可以是https的加密的域名。

在D-Laravel的etc目錄下，會多出v3.ext及default-ssl.conf的設定檔。

設計上，所有的project都應放在sites的資料夾內，不然./console及./create會運作不正確。
