### ISSUE TITLE
PHP 7.4.16

### ISSUE THREAD

**Issue by sorasu** [DevinY/dlaravel#7]
PHP 7.4.16 doesn't support JPEG and EXIF
version 7.3.4 has no such issue though
is it possible you add those extension to 7.4.16?

**Comment by DevinY** [comment]
Hi, I just pushed new image for php 7.4.16.
You can get the new image with following command:
docker pull deviny/fpm:7.4.16
I also updated the deviny/fpm:8.0.3 image.

<img width="1282" alt="截圖 2021-04-08 上午1 53 49" src="https://user-images.githubusercontent.com/7411903/113912513-ca3e2800-980d-11eb-8b52-24dcdcf70fb1.png">

**Comment by DevinY** [comment]
For more info about the gd and exif.
You have to add your extension ini files into the  etc/php folder of D-Laravel.
or just add extension into dlaravel.ini file.

You can type command "./console ext" to make sure that the exif.so is show up.

<img width="738" alt="截圖 2021-04-08 上午2 26 55" src="https://user-images.githubusercontent.com/7411903/113916096-286d0a00-9812-11eb-8d46-323b6101164c.png">

<img width="1134" alt="截圖 2021-04-08 上午2 30 29" src="https://user-images.githubusercontent.com/7411903/113916348-73871d00-9812-11eb-8d7f-c2f81885761d.png">

**Comment by sorasu** [comment]
updated, and now I can run my sites on php 7.4.16 smoothly.
thanks!
